apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::499816354495:role/qohashing-eks-cluster-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::499816354495:user/cloud_user
      username: cloud_user
      groups:
        - system:masters

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::499816354495:role/qohashing-eks-cluster-eks-node-role\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2020-05-24T23:10:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1836"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c5a5df73-9e13-11ea-985a-0e612f20cee3
