apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-24T23:50:36Z"
  labels:
    app: weqohash-webapp
  name: qserv
  namespace: default
  resourceVersion: "5336"
  selfLink: /api/v1/namespaces/default/services/qserv
  uid: 5d09739f-9e19-11ea-9be2-0a9cc767fd01
spec:
  clusterIP: 172.20.58.85
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30259
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: weqohash-webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a5d09739f9e1911ea9be20a9cc767fd0-1937763540.us-east-1.elb.amazonaws.com
