apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weqohash-webapp
  name: weqohash-webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weqohash-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weqohash-webapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
